### ISSUE TITLE
Finalize website wireframes and overall design 

### ISSUE THREAD

**Issue by eskelProgramming** [eskelProgramming/CrosswordWallTile#14]
Using [Excalidraw](https://excalidraw.com/):
- [x] Finalize wireframes
- [x] Get them approved by the client
- [x] Finalize class designs and methods
- [x] Implement the wireframes and class designs into the Wiki page

**Comment by eskelProgramming** [comment]
After a discussion with the client, the following changes need to be taken into account:
- [ ] There should be a way for the user to change the Stain color underneath the crossword generation / product page and there should also be a way to change the font color where applicable
- [ ] The user should not have to login to use anything on the customer side, but if they want to save their cart they will be required to sign in. 
- [ ] There will be design Frames that can be added to the cart. Each Frame has three different sizes. A Frame is a Product. 
- [ ] When added manually, tiles will be entered as the name, and the tiles will be added to the cart dynamically. 
- [ ] After the user adds all of their products, there will be a popup that will require the user to input the size of their wall. It will then show a grid that will represent the size of the wall. The user will be able to move and modify all products. If the size of the products exceeds the size of the wall a warning should popup and tell the user that their selections need to be modified. The client would also potentially like the user to be able to upload a photo of their wall in order to see what the final product would look like. The photo SHOULD NOT be saved into the database.

**Comment by eskelProgramming** [comment]
The most recent changes have been approved by the client. This is the current wireframe version:

![Wireframesv2](https://github.com/user-attachments/assets/39048b3b-1ad5-4ff9-81fa-c0988d19fd62)

**Comment by eskelProgramming** [comment]
Tentative Class diagram:
![ClassesV2](https://github.com/user-attachments/assets/6cb11513-30fa-4f91-90fd-097aa1aeff01)

**Comment by eskelProgramming** [comment]
The wireframes and class diagram have been added to the [wiki](https://github.com/eskelProgramming/CrosswordWallTile/wiki).
